# -*- coding: utf-8 -*-
"""
Written by Daniel M. Aukes.
Email: danaukes<at>seas.harvard.edu.
Please see LICENSE.txt for full license.
"""
import PySide.QtGui as qg
import popupcad
import os

icon = {}
icon['angle'] = 'angle.png'
icon['bufferop'] = 'bufferop.png'
icon['circle'] = 'circle.png'
icon['distance'] = 'distance.png'
icon['distancex'] = 'distancex.png'
icon['distancey'] = 'distancey.png'
icon['equal'] = 'equal.png'
icon['export'] = 'export.png'
icon['hingefoldop'] = 'hingefoldop.png'
icon['horizontal'] = 'horizontal.png'
icon['icons'] = 'icons.png'
icon['import'] = 'import.png'
icon['convex_hull'] = 'convex_hull.png'
icon['layerop'] = 'layerop.png'
icon['layers'] = 'layers.png'
icon['line'] = 'line.png'
icon['locate'] = 'locate.png'
icon['metaop'] = 'metaop.png'
icon['new'] = 'new.png'
icon['open'] = 'open.png'
icon['operations'] = 'operations.png'
icon['parallel'] = 'parallel.png'
icon['perpendicular'] = 'perpendicular.png'
icon['placeop'] = 'placeop.png'
icon['pointline'] = 'pointline.png'
icon['polygon'] = 'polygon.png'
icon['polygons'] = 'polygons.png'
icon['polyline'] = 'polyline.png'
icon['quit'] = 'quit.png'
icon['rectangle'] = 'rectangle.png'
icon['redo'] = 'redo.png'
icon['refresh'] = 'refresh.png'
icon['save'] = 'save.png'
icon['undo'] = 'undo.png'
icon['vertical'] = 'vertical.png'
icon['outersheet'] = 'outersheet.png'
icon['outerweb'] = 'outerweb.png'
icon['autosupport'] = 'autosupport.png'
icon['firstpass'] = 'firstpass.png'
icon['secondpass'] = 'secondpass.png'
icon['triangulate'] = 'triangulate.png'
icon['showconstraints'] = 'showconstraints.png'
icon['coincident'] = 'coincident.png'
icon['getjoints'] = 'getjoints.png'
icon['points'] = 'points.png'
icon['text'] = 'text.png'
icon['identifybodies'] = 'identifybodies.png'
icon['removability'] = 'removability.png'
icon['scrap'] = 'scrap.png'
icon['cleanup'] = 'cleanup.png'
icon['shiftflip'] = 'shiftflip.png'
icon['shiftflip2'] = 'shiftflip2.png'
icon['broom'] = 'broom.png'
icon['getjoints2'] = 'getjoints2.png'
icon['customsupport'] = 'customsupport.png'
icon['dotdotdot'] = 'dotdotdot.png'
icon['simplify'] = 'simplify.png'
icon['pointer'] = 'pointer.png'
icon['printapede'] = 'printapede.png'
icon['hand'] = 'hand.png'

